on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build_project:
    runs-on: ubuntu-latest
    name: Build Project
    environment: ${{ github.event_name != 'pull_request' && 'github-pages' || '' }}
    steps:
      - name: Cleanup to free disk space
        uses: jlumbroso/free-disk-space@54081f138730dfa15788a46383842cd2f914a1be
        with:
          tool-cache: false
          android: true
          dotnet: false
          haskell: false
          large-packages: false
          docker-images: false
          swap-storage: false

      - name: Checkout project
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          fetch-depth: 0

      - name: Build the project
        uses: leanprover/lean-action@c544e89643240c6b398f14a431bcdc6309e36b3e
        with:
          use-github-cache: true

      - name: Build blueprint with local tools
        uses: xu-cheng/texlive-action@f886de8159e5952a131848a5fa9c3196a2132b5d
        with:
          docker_image: ghcr.io/xu-cheng/texlive-full:20250401
          run: |
            apk update && apk add --update make py3-pip git pkgconfig graphviz graphviz-dev gcc musl-dev
            git config --global --add safe.directory $GITHUB_WORKSPACE
            python3 -m venv env && source env/bin/activate
            pip install --upgrade pip requests wheel
            pip install pygraphviz --config-settings="--global-option=build_ext" \
              --config-settings="--global-option=-L/usr/lib/graphviz/" \
              --config-settings="--global-option=-R/usr/lib/graphviz/"
            pip install -e ./tools/plastexdepgraph
            pip install -e ./tools/leanblueprint
            cd blueprint && leanblueprint pdf && leanblueprint web && cd ..
            mkdir -p docs && cp blueprint/print/print.pdf docs/blueprint.pdf
            cp -r blueprint/web docs/blueprint

      - name: Check blueprint declarations
        run: lake exe checkdecls blueprint/lean_decls

      - name: Compile documentation and deploy
        uses: leanprover-community/docgen-action@deed0cdc44dd8e5de07a300773eb751d33e32fc8
        with:
          blueprint: false
          deploy: ${{ github.event_name != 'pull_request' }}
